config/routes.rb
Rails.application.routes.draw do
  root 'streets#console'
  resources :streets, except: [:index, :create, :new]
  
  get '/streets', to: 'streets#console', as: :streets_index
  get '/new_street', to: 'streets#new'
  post '/new_street', to: 'streets#create'

  get '/search', to: 'streets#search', as: :streets_search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/street.rb
class Street < ApplicationRecord
	def self.search(search)
  where("name LIKE ? OR borough LIKE ?", "%#{search}%", "%#{search}%") 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController

  def console
    @streets = Street.all
  end

  def new
    @street = Street.new
  end

  def create
    @streets = Street.all
    @street = Street.new(street_params)
    respond_to do |format|
      if @street.save
        format.js
      end
    end
  end
  
  def show
    @street = Street.find(params[:id])
  end

  def search
    @streets = Street.all
    respond_to do |format|
      if params[:search]
    @streets = Street.search(params[:search]).order("created_at DESC")
    format.js
      else
    @streets = Street.all.order("created_at DESC")
    format.js
    end
  end
end

  def edit
    
  end

  def update

  end

  def destroy
  end

  private

  def street_params
    params.require(:street).permit(:name, :borough, :left_side, :right_side, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_console.html.erb
asasadad

app/views/partials/_create_street_form.html.erb
<div id="street_form">
   <h3>Add Street</h3>
   <%= form_for :street, url: new_street_path, remote: true do |s| %>
   <%= s.text_field :name, placeholder: 'Street name'%>
   <h4>Borough</h4>
   <%= select(:street, :borough, [['Brooklyn', 'Brooklyn'], ['Queens', 'Queens'],['Manhattan', 'manhattan'], ['Staten Island', 'Staten Island'], ['Bronx', 'Bronx']]) %>
   <h4>Left Side</h4>
   <%= select(:street, :left_side, [['Mon', 'Mon'],['Tues', 'Tues'],['Wed', 'Wed'],['Th', 'Th'],['F', 'F'],['Sat', 'Sat'],['Sun', 'Sun']]) %> 
   <h4>Right Side</h4>
   <%= select(:street, :right_side, [['Mon', 'Mon'],['Tues', 'Tues'],['Wed', 'Wed'],['Th', 'Th'],['F', 'F'],['Sat', 'Sat'],['Sun', 'Sun']]) %> 
   <h4>Start Time</h4>
   <%= s.time_select :start_time %>
   <h4>End Time</h4>
   <%= s.time_select :end_time %>
   <br>
   <br>
   <%= s.submit 'Create', class: 'btn btn-primary' %>
   <% end %>
</div>

app/views/partials/_search_form.html.erb
<h4>Search for streets</h4>
<div id="search_form">
	<%= form_tag streets_search_path, method: 'get', remote: true do %>
		<p>
			<%= text_field_tag :search, params[:search], placeholder: "Search Streets" %>
			<%= submit_tag "Search", :name => nil %>
		</p>
	<% end %>
</div>

app/views/partials/_searched_streets.html.erb
<% if @streets.present? %>
	<%= render "partials/streets", remote: true %>
<% end %>

app/views/partials/_streets.html.erb
<% if params[:search]%>
	<ul class="list-group">
		<% @streets.each do |street| %>
		<li class="list-group-item">Street Name:<%= street.name %></li>
		<li class="list-group-item">Borough:<%= street.borough %></li>
		<li class="list-group-item">Left Side Days:<%= street.left_side %></li>
		<li class="list-group-item">Right Side Days:<%= street.right_side %></li>
		<li class="list-group-item">Start Time:<%= street.start_time.strftime("%l"":""%M") %></li>
		<li class="list-group-item">End Time:<%= street.end_time.strftime("%l"":""%M") %></li>
	</ul>
	<% end %>
<% end %>

app/views/streets/console.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<!--   <#%= image_tag ('cars_night.jpg') %>
 --></head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-xs-4 street-form">
      <span class ="street-form"><%= render 'partials/create_street_form',remote: true%></span>
      <br>
      </div>
     <div class="col-md-2 search-form">
        <span class ="search-form"><%= render 'partials/search_form', remote: true%></span>
        <span class ="searched-streets"><%= render 'partials/searched_streets', remote: true%></span>
    </div>
  </div>
</div>  
</body>
</html>

app/views/streets/create.js.erb
$('.street-form').html('<%= j render 'partials/create_street_form' %>')
$('#street_name').val('');

app/views/streets/search.js.erb
$('.searched-streets').html('<%= j render 'partials/searched_streets' %>');
$('.searched-streets').val('')